-- MySQL Script generated by MySQL Workbench
-- Thu Sep 21 14:36:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`especies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`especies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`especies` (
  `especies_id` INT NOT NULL AUTO_INCREMENT,
  `especies_descricao` VARCHAR(45) NOT NULL,
  `especies_cancelado` TINYINT NULL,
  PRIMARY KEY (`especies_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`unidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`unidades` (
  `unidades_id` INT NOT NULL,
  `unidades_descricao` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`unidades_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `produtos_id` INT NOT NULL AUTO_INCREMENT,
  `produtos_descricao` VARCHAR(45) NOT NULL,
  `produtos_quantidade` FLOAT NOT NULL,
  `produtos_especies_id` INT NOT NULL,
  `produtos_cancelado` TINYINT NULL,
  `produtos_unidade` INT NOT NULL,
  `produtos_custo` FLOAT NULL,
  `produtos_valor` FLOAT NOT NULL,
  PRIMARY KEY (`produtos_id`),
  INDEX `fk_produtos_especies_idx` (`produtos_especies_id` ASC) VISIBLE,
  INDEX `fk_produtos_unidades_idx` (`produtos_unidade` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_especies`
    FOREIGN KEY (`produtos_especies_id`)
    REFERENCES `mydb`.`especies` (`especies_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_unidades`
    FOREIGN KEY (`produtos_unidade`)
    REFERENCES `mydb`.`unidades` (`unidades_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pessoas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pessoas` (
  `pessoas_id` INT NOT NULL AUTO_INCREMENT,
  `pessoas_cpf` VARCHAR(11) NULL,
  `pessoas_nome` VARCHAR(45) NOT NULL,
  `pessoas_email` VARCHAR(45) NULL,
  `pessoas_telefone` VARCHAR(17) NULL,
  `pessoas_endereco` VARCHAR(100) NOT NULL,
  `pessoas_cancelado` TINYINT NULL,
  PRIMARY KEY (`pessoas_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`funcionarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios` (
  `funcionariios_id` INT NOT NULL AUTO_INCREMENT,
  `funcionarios_salario` FLOAT NOT NULL,
  `funcionarios_admissao` DATE NOT NULL,
  `funcionarios_demissao` DATE NULL,
  `funcionarios_pessoas_id` INT NOT NULL,
  PRIMARY KEY (`funcionariios_id`),
  INDEX `fk_funcionarios_pessoas_idx` (`funcionarios_pessoas_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_pessoas`
    FOREIGN KEY (`funcionarios_pessoas_id`)
    REFERENCES `mydb`.`pessoas` (`pessoas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vendas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vendas` (
  `vendas_id` INT NOT NULL AUTO_INCREMENT,
  `vendas_clientes_id` INT NOT NULL,
  `vendas_funcionarios_id` INT NOT NULL,
  `vendas_data` DATETIME NOT NULL,
  `vendas_cancelado` TINYINT NULL,
  PRIMARY KEY (`vendas_id`),
  INDEX `fk_vendas_clientes_idx` (`vendas_clientes_id` ASC) VISIBLE,
  INDEX `fk_vendas_funcionarios_idx` (`vendas_funcionarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_pessoas`
    FOREIGN KEY (`vendas_clientes_id`)
    REFERENCES `mydb`.`pessoas` (`pessoas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_funcionarios`
    FOREIGN KEY (`vendas_funcionarios_id`)
    REFERENCES `mydb`.`funcionarios` (`funcionariios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fornecedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fornecedores` (
  `fornecedores_id` INT NOT NULL AUTO_INCREMENT,
  `fornecedores_cnpj` VARCHAR(14) NOT NULL,
  `fornecedores_razao_social` VARCHAR(45) NOT NULL,
  `fornecedores_telefone` VARCHAR(17) NULL,
  `fornecedores_endereco` VARCHAR(100) NULL,
  `fornecedores_cancelado` TINYINT NULL,
  PRIMARY KEY (`fornecedores_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entradas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entradas` (
  `entradas_id` INT NOT NULL AUTO_INCREMENT,
  `entradas_funcionarios_id` INT NOT NULL,
  `entradas_data` DATETIME NULL,
  `entradas_cancelado` TINYINT NULL,
  `entradas_fornecedores_id` INT NOT NULL,
  PRIMARY KEY (`entradas_id`),
  INDEX `fk_entradas_funcionarios_idx` (`entradas_funcionarios_id` ASC) VISIBLE,
  INDEX `fk_entradas_fornecedores_idx` (`entradas_fornecedores_id` ASC) VISIBLE,
  CONSTRAINT `fk_entradas_funcionarios`
    FOREIGN KEY (`entradas_funcionarios_id`)
    REFERENCES `mydb`.`funcionarios` (`funcionariios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entradas_fornecedores`
    FOREIGN KEY (`entradas_fornecedores_id`)
    REFERENCES `mydb`.`fornecedores` (`fornecedores_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos_fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produtos_fornecedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produtos_fornecedores` (
  `produtos_fornecedores_id` INT NOT NULL AUTO_INCREMENT,
  `produtos_fornecedores_produtos_id` INT NOT NULL,
  `produtos_fornecedores_fornecedores_id` INT NOT NULL,
  `produtos_fornecedores_cancelado` TINYINT NULL,
  PRIMARY KEY (`produtos_fornecedores_id`),
  INDEX `fk_produtos_fornecedores_produtos_idx` (`produtos_fornecedores_produtos_id` ASC) VISIBLE,
  INDEX `fk_produtos_fornecedores_fornecedores_idx` (`produtos_fornecedores_fornecedores_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_fornecedores_produtos`
    FOREIGN KEY (`produtos_fornecedores_produtos_id`)
    REFERENCES `mydb`.`produtos` (`produtos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_fornecedores_fornecedores`
    FOREIGN KEY (`produtos_fornecedores_fornecedores_id`)
    REFERENCES `mydb`.`fornecedores` (`fornecedores_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendas_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vendas_produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vendas_produtos` (
  `vendas_produtos_id` INT NOT NULL,
  `vendas_produtos_produtos_id` INT NOT NULL,
  `vendas_produtos_vendas_id` INT NOT NULL,
  `vendas_produtos_quantidade` FLOAT NOT NULL,
  `vendas_produtos_cancelado` TINYINT NULL,
  `vendas_valor` FLOAT NOT NULL,
  PRIMARY KEY (`vendas_produtos_id`),
  INDEX `fk_vendas_produtos_vendas_idx` (`vendas_produtos_vendas_id` ASC) VISIBLE,
  INDEX `fk_vendas_produtos_produtos_idx` (`vendas_produtos_produtos_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_produtos_vendas`
    FOREIGN KEY (`vendas_produtos_vendas_id`)
    REFERENCES `mydb`.`vendas` (`vendas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_produtos_produtos`
    FOREIGN KEY (`vendas_produtos_produtos_id`)
    REFERENCES `mydb`.`produtos` (`produtos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entradas_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entradas_produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entradas_produtos` (
  `entradas_produtos_id` INT NOT NULL AUTO_INCREMENT,
  `entradas_produtos_produtos_id` INT NOT NULL,
  `entradas_produtos_entradas_id` INT NOT NULL,
  `entradas_produtos_quantidade` FLOAT NULL,
  `entradas_produtos_valor` FLOAT NULL,
  `entradas_produtos_cancelado` TINYINT NULL,
  PRIMARY KEY (`entradas_produtos_id`),
  INDEX `fk_entradas_produtos_produtos_idx` (`entradas_produtos_produtos_id` ASC) VISIBLE,
  INDEX `fk_entradas_produtos_entradas_idx` (`entradas_produtos_entradas_id` ASC) VISIBLE,
  CONSTRAINT `fk_entradas_produtos_produtos`
    FOREIGN KEY (`entradas_produtos_produtos_id`)
    REFERENCES `mydb`.`produtos` (`produtos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entradas_produtos_entradas`
    FOREIGN KEY (`entradas_produtos_entradas_id`)
    REFERENCES `mydb`.`entradas` (`entradas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
